config/urls.py
from django.contrib import admin

from django.urls import path,include

#   path(URL,処理(もしくは参照する他のurls.py),逆引き用の名前(テンプレートのurlで使う))
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo.urls"),name="todo"),
]

todo/urls.py
from django.urls import path
from . import views

app_name    = "todo"
urlpatterns = [ 
    path('', views.index, name="index"),
]

todo/models.py
from django.db import models

# Create your models here.

#uuidはPythonの標準モジュール
import uuid

class Todolist(models.Model):

    class Meta:
        db_table = "todolist"

    #UUID、締め切り、やること。モデルのフィールドに関しては教科書P47を参照。CharFieldについてはオプションとしてmax_lengthの指定必須。オプションはP48を参照
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    deadline    = models.DateTimeField(verbose_name="期限")
    content     = models.CharField(verbose_name="やること",max_length=100)

    def __str__(self):
        return self.content

todo/forms.py
#モデルのフィールド定義を継承し、フォームとする。
from .models import Todolist
from django import forms
from django.forms import ModelForm,Textarea,DateTimeInput


#ModelFormを継承し、Metaクラスに利用するモデルクラス名、フィールド、ウィジェット等を記述。モデルを継承したフォームは教科書P91を参照。
class TodolistForm(ModelForm):
    class Meta:
        model   = Todolist
        widgets = { "deadline":DateTimeInput(attrs={"class":"form-control my-2","autofocus":"","value":"2020-09-17 14:30:00"} ),
                    "content":Textarea(attrs={"class":"form-control my-2","placeholder":"ここにやることを入力する","rows":"3"} ),
                    }
        fields  = [ "deadline","content" ]


#モデルを継承せずにフォームを1から作る場合は、Formを継承
#【注意】モデルで定義したidは編集不可(editable=False)の要素のため、継承することができない
class TododeleteForm(forms.Form):
    todo_delete  = forms.UUIDField()

todo/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View

#モデルとフォームを読み込む
from .models import Todolist
from .forms import TodolistForm,TododeleteForm


from django.utils import timezone

#Viewを継承してGET文、POST文の関数を作る。教科書P35にクラスベースのビュー関数の書き方が解説されている
class TodoView(View):

    def reference(self):
        form        = TodolistForm()
        data        = Todolist.objects.order_by("deadline")

        return form,data

    def get(self, request, *args, **kwargs):

        form,data   = self.reference()
        context     = { "data"  : data,
                        "form"  : form }

        #render(レスポンス返すために必要になるリクエスト,レンダリングするテンプレートのパス,レンダリング対象に与える変数)
        return render(request,"todo/index.html",context)

    def post(self, request, *args, **kwargs):

        #TODOリストの作成
        if "deadline" in request.POST and "content" in request.POST:

            #教科書P87の『ビューでの利用例』を参照。フォームのバリデーション結果で処理を切り替える
            formset = TodolistForm(request.POST)
            if formset.is_valid():
                formset.save()
            else:
                print("バリデーションエラー")
        

        #TODOリストの削除
        if "todo_delete" in request.POST:
            
            formset = TododeleteForm(request.POST)
            if formset.is_valid():

                #バリデーションOKの場合、受け取った内容をクリーン化(教科書P94の緑部分)、削除のクエリを実行させる(fillterは教科書P57、deleteはP62)
                clean_data  = formset.clean()
                Todolist.objects.filter(id=clean_data["todo_delete"]).delete()
            else:
                print("バリデーションエラー")


        form,data   = self.reference()
        context     = { "data"  : data,
                        "form"  : form }

        return render(request,"todo/index.html",context)

#↓クラスベースのビューを関数化させるメソッドが.as_view()。教科書P36と config/urls.pyの英語の解説部分を参照
index       = TodoView.as_view()

templates/todo/index.html
{% load static %}

<!-- ↑静的ファイル配信先のURLを読み込んでいる。教科書P77-->

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>TODOリスト管理ツール</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <link rel="stylesheet" href="{% static 'todo/css/style.css' %}">
    <!-- ↑静的ファイルの読み込み。パスはstatic以下を記述 教科書P77-->
</head>
<body>
    <header class="bg-primary">
        <!-- ↓URLの逆引き処理。教科書P78-->
        <a href="{% url 'todo:index' %}"><h1 class="text-center text-white">TODOリスト管理ツール</h1></a>
    </header>

    <!--波括弧を使用して変数もしくは処理を実行する、これがDTL(Django Template Language)。教科書P69
        
        なぜ波括弧なのか？→通常のPythonで使用する記号ではHTMLと競合するから -->
    <main class="container">

        <form action="" method="post">
            {% csrf_token %}
            <!-- formとそのまま書いても良いが、自動的にテーブルタグで囲まれるので注意 -->
            {{ form.deadline }}
            {{ form.content }}
            <input class="form-control my-2" type="submit" value="送信">
        </form>

        <table>
            <thead>
                <tr>
                    <td>期限</td>
                    <td>やること</td>
                    <td>削除</td>
                </tr>
            </thead>
            <tbody>
                <!--ここがやることリスト、ループさせる 教科書P75-->
                {% for todo_data in data %}
                <tr>
                    <td class="text-center">{{ todo_data.deadline }}</td>
                    <!--↓フィルタのlinebreaksbrは改行をBRタグとして処理をする。改行込みの文字列を表示する際に使う。教科書P71-->
                    <td>{{ todo_data.content|linebreaksbr }}</td>
                    <td class="trash">
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="todo_delete" value="{{ todo_data.id }}">
                            <input id="todo_delete_{{ todo_data.id }}" type="submit" style="display:none;">
                            <label for="todo_delete_{{ todo_data.id }}"><i class="fas fa-trash-alt"></i></label>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </main>


</body>
</html>